kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1
images:
- name: am
  newName: us-docker.pkg.dev/forgeops-public/images/am
  newTag: 8.0.2
- name: am-custom
  newName: busybox
  newTag: musl
- name: amster
  newName: us-docker.pkg.dev/forgeops-public/images/amster
  newTag: 8.0.2
- name: ds
  newName: us-docker.pkg.dev/forgeops-public/images/ds
  newTag: 8.0.2
- name: idm
  newName: us-docker.pkg.dev/forgeops-public/images/idm
  newTag: 8.0.1
- name: idm-custom
  newName: busybox
  newTag: musl
- name: ig
  newName: us-docker.pkg.dev/forgeops-public/images/ig
  newTag: 8.0.2
- name: admin-ui
  newName: us-docker.pkg.dev/forgeops-public/images/admin-ui
  newTag: 8.0.1
- name: end-user-ui
  newName: us-docker.pkg.dev/forgeops-public/images/end-user-ui
  newTag: 8.0.1
- name: login-ui
  newName: us-docker.pkg.dev/forgeops-public/images/login-ui
  newTag: 8.0.1
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: identity-platform
namespace: pnguat
