apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../image-defaulter

resources:
  - ../../../vendor/forgeops-2026.1/ds/cts

patches:
  - path: sts.yaml
  
namespace: forgerock
