apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/runtime/ds-idrepo
  - ../../components/runtime/ds-cts
  - ../../components/runtime/am
  - ../../components/runtime/idm
  - ../../components/runtime/admin-ui
  - ../../components/runtime/login-ui
  - ../../components/runtime/end-user-ui

  - ../../components/platform/nginx
  - ../../components/platform/routes
  - ../../components/platform/replication-network/dr

  - ../../components/security/pki/shared
  - ../../components/security/pki/dr
