apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-ssl-cert
  namespace: forgerock
spec:
  commonName: ds
  dnsNames:
    - '*.ds'
    - '*.ds-idrepo'
    - '*.ds-cts'
    - ds-idrepo-0.ds-idrepo.forgerock.svc.cluster.local
    - ds-idrepo-0.dr.internal
    - ds-idrepo-0.primary.replication.crc.lab
  duration: 175200h
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: forgerock-ca-issuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Never
  secretName: ds-ssl-keypair
  secretTemplate:
    annotations:
      my-secret-annotation: cert-manager-generated
    labels:
      app: ds
  subject:
    organizations:
      - forgerock.org
  usages:
    - server auth
    - client auth
