apiVersion: route.openshift.io/v1
kind: Route

metadata:
  name: iam-gateway
  namespace: pnguat

spec:
  host: ping-uat.apps.pnguat.arabbanking.local

  to:
    kind: Service
    name: fr-proxy
    weight: 100

  port:
    targetPort: http

  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

  wildcardPolicy: None
