apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-proxy-config-map.yaml
  - fr-proxy-svc.yaml
  - fr-proxy-deploy.yaml
  - iam-gateway-route.yaml
namespace: pnguat
